Repository hashicorp/terraform-schema, pull requests merged in 2022-08, with the labels that each got.

#128 Enable module source and version completion
  earlydecoder/decoder_test.go
  earlydecoder/load_module.go
  go.mod
  go.sum
  internal/schema/0.12/module_block.go
  internal/schema/0.13/module_block.go
  internal/schema/universal/module_block.go
  module/module_calls.go
  schema/module_schema_test.go
Labels: enhancement

#130 earlydecoder: avoid crash by validating provider names
  earlydecoder/decoder.go
  earlydecoder/decoder_test.go
Labels: bug

#129 schema: Introduce CoreModuleSchemaForConstraint
  go.mod
  go.sum
  internal/schema/0.14/provisioners.go
  internal/schema/0.14/root.go
  internal/schema/0.15/root.go
  internal/schema/0.15/terraform.go
  internal/schema/1.1/root.go
  internal/schema/1.1/terraform.go
  internal/schema/1.2/root.go
  internal/versiongen/gen.go
  internal/versiongen/gen_test.go
  schema/core_schema.go
  schema/core_schema_test.go
  schema/errors.go
  schema/versions_gen.go
Labels: enhancement

#131 versiongen: fix test logic
  internal/versiongen/gen_test.go
Labels: bug

#138 Bump `hcl-lang` to `1fce4f`
  go.mod
  go.sum
Labels: dependencies

#137 Update static pointer `BlockSchema` definitions to function calls
  internal/schema/0.12/locals_block.go
  internal/schema/0.12/module_block.go
  internal/schema/0.12/output_block.go
  internal/schema/0.12/root.go
  internal/schema/0.13/module_block.go
  internal/schema/0.13/provider_block.go
  internal/schema/0.13/root.go
  internal/schema/1.2/data.go
  internal/schema/1.2/output.go
  internal/schema/1.2/resource.go
  internal/schema/1.2/root.go
Labels: bug
