Repository hashicorp/terraform-schema, pull requests merged in 2023-11, with the labels that each got.

#290 Allow variable references in `depends_on`
  internal/schema/0.12/data_block.go
  internal/schema/0.12/output_block.go
  internal/schema/0.12/resource_block.go
  internal/schema/0.13/module_block.go
  internal/schema/1.5/check.go
Labels: bug

#288 Fix provider attribute to block conversion
  schema/convert_json.go
  schema/convert_json_test.go
Labels: bug

#289 Skip inferring module inputs for default values
  go.mod
  go.sum
  internal/schema/0.12/variable_block.go
  internal/schema/0.14/variable_block.go
  schema/module_schema.go
  schema/module_schema_test.go
  schema/variable_schema.go
  schema/variable_schema_test.go
Labels: bug

#292 Allow local references in `depends_on`
  go.mod
  go.sum
  internal/schema/0.12/data_block.go
  internal/schema/0.12/locals_block.go
  internal/schema/0.12/output_block.go
  internal/schema/0.12/resource_block.go
  internal/schema/0.13/module_block.go
  internal/schema/1.5/check.go
Labels: bug

#294 github: Disable dependabot for GHA
  .github/dependabot.yml
Labels: dependencies, ci

#296 Update version resolution for empty constraints
  schema/versions.go
  schema/versions_gen.go
  schema/versions_test.go
Labels: bug

#295 Add `skip_s3_checksum` attribute to s3 backend
  internal/schema/backends/backends.go
  internal/schema/backends/s3.go
Labels: enhancement

#301 backend/s3: Reflect new proxy settings
  internal/schema/backends/backends.go
  internal/schema/backends/s3.go
  schema/versions_gen.go
Labels: enhancement

#302 backend/s3: Reflect SSO endpoint override
  internal/schema/backends/s3.go
Labels: enhancement

#303 Fix Terraform version for `skip_s3_checksum` (s3 backend)
  internal/schema/backends/backends.go
  internal/schema/backends/s3.go
Labels: bug
